FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV POETRY_VERSION=1.8.3

WORKDIR /tmp

COPY poetry.lock pyproject.toml ./

SHELL [ "/bin/bash", "-euxo", "pipefail", "-c" ]

RUN pip install --no-cache-dir "poetry==$POETRY_VERSION" && \
    poetry export --without-hashes --without dev --format requirements.txt | pip install --no-cache-dir -r /dev/stdin

WORKDIR /bot

COPY . .

ENTRYPOINT [ "python" ]
CMD [ "-m", "bot" ]
