version: '3.8'

services:
  api:
    build:
      context: .
      target: api-dev
      dockerfile: Dockerfile.dev
    image: kvdomingo/chaebot-api:latest
    env_file: .env
    volumes:
      - .:/bot

  bot:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.dev
    image: kvdomingo/chaebot-dev:latest
    env_file: .env
    volumes:
      - .:/bot
    restart: unless-stopped
    depends_on:
      - api

  docs:
    image: node:18-alpine
    environment:
      - NODE_ENV=development
    working_dir: /web
    entrypoint:
      - /bin/sh
      - "-c"
      - "yarn install && exec yarn dev --host 0.0.0.0 --port 3000"
    volumes:
      - ./docs:/web

  proxy:
    image: bitnami/nginx:latest
    environment:
      - NGINX_HTTP_PORT_NUMBER=${HTTP_PORT}
    volumes:
      - ./proxy:/opt/bitnami/nginx/conf/server_blocks:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chaebot.rule=Host(`chaebot.localhost`)"
      - "traefik.http.routers.chaebot.entrypoints=http"
      - "traefik.http.routers.chaebot.middlewares=secured@file"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.chaebot.loadbalancer.server.port=${HTTP_PORT}"
    restart: unless-stopped
    networks:
      - default
      - gateway

  postgres:
    image: bitnami/postgresql:13
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db-data:/bitnami/postgresql

networks:
  gateway:
    external: true

volumes:
  db-data:
