version: "3.8"

services:
  api:
    build:
      context: .
      target: api-dev
    image: kvdomingo/kvisualapi:latest
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/bot
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - 'while [[ "$$(curl -s -o /dev/null -I -L -w ''%{http_code}'' http://api:8000/admin/)" != "200" ]]; do echo ..; sleep 5; done;'
      interval: 5s
      timeout: 10s
      retries: 3

  docs:
    build:
      context: .
      target: web-dev
    image: kvdomingo/kvisualdocs:latest
    env_file: web/app/.env
    ports:
      - 3000:3000
    volumes:
      - .:/bot

  bot:
    build:
      context: .
      target: dev
    image: kvdomingo/kvisualbot:latest
    env_file: .env
    volumes:
      - .:/bot
    restart: always
    depends_on:
      api:
        condition: service_healthy
