services:
  bot:
    build: .
    image: ghcr.io/kvdomingo/hannibot
    restart: unless-stopped
    init: true
    env_file: .env
    volumes:
      - .:/bot
      - venv-data:/bot/.venv

  docs:
    image: oven/bun:1.1-alpine
    restart: unless-stopped
    init: true
    environment:
      NODE_ENV: development
    working_dir: /app
    entrypoint:
      - /bin/sh
      - -eu
      - -c
      - "bun install && exec bun run dev"
    volumes:
      - ./docs:/app
    ports:
      - 3000:3000

  db:
    image: bitnami/postgresql:13.6.0-debian-10-r19
    restart: unless-stopped
    env_file: .env
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - db-data:/bitnami/postgresql
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:8.12
    env_file: .env
    environment:
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5000
    volumes:
      - pgadmin-data:/pgadmin4
    ports:
      - 5000:5000

volumes:
  db-data:
  venv-data:
  pgadmin-data:
