version: '3.8'

services:
  api:
    build:
      context: .
      target: api-dev
      dockerfile: dev.Dockerfile
    image: kvdomingo/kvisualapi:latest
    env_file: .env
    volumes:
      - .:/bot

  bot:
    build:
      context: .
      target: dev
      dockerfile: dev.Dockerfile
    image: kvdomingo/kvisualbot:latest
    env_file: .env
    volumes:
      - .:/bot
    restart: unless-stopped
    depends_on:
      - api

  docs:
    image: node:16-alpine
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling
      - WDS_SOCKET_PORT=0
    working_dir: /web
    entrypoint:
      - /bin/sh
      - "-c"
      - "yarn install && yarn start"
    volumes:
      - ./web/app:/web

  proxy:
    image: bitnami/nginx:latest
    environment:
      - NGINX_HTTP_PORT_NUMBER=${HTTP_PORT}
    volumes:
      - ./proxy:/opt/bitnami/nginx/conf/server_blocks:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kvisualbot.rule=Host(`kvisualbot.localhost`)"
      - "traefik.http.routers.kvisualbot.entrypoints=http"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.kvisualbot.loadbalancer.server.port=${HTTP_PORT}"
    restart: unless-stopped
    networks:
      - default
      - gateway

  postgres:
    image: bitnami/postgresql:13
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db-data:/bitnami/postgresql

networks:
  gateway:
    external: true

volumes:
  db-data:
