services:
  api:
    build:
      context: .
      target: api-dev
      dockerfile: Dockerfile.dev
    image: kvdomingo/chaebot-api:latest
    env_file: .env
    volumes:
      - .:/bot
    ports:
      - 5000:5000

  bot:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.dev
    image: kvdomingo/chaebot-dev:latest
    environment:
      CLOUDSDK_CONFIG: /opt/gcloud
    env_file: .env
    volumes:
      - .:/bot
      - ${HOME}/.config/gcloud:/opt/gcloud
    restart: unless-stopped
    depends_on:
      - api

  docs:
    image: oven/bun:1.1-alpine
    environment:
      NODE_ENV: development
    working_dir: /app
    entrypoint:
      - /bin/sh
      - "-c"
      - "bun install && exec bun run dev"
    volumes:
      - ./docs:/app
    ports:
      - 3000:3000

  postgres:
    image: bitnami/postgresql:13.15.0-debian-12-r19
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db-data:/bitnami/postgresql
    ports:
      - 5432:5432

volumes:
  db-data:
