[tool.poetry]
name = "kvisualbot"
version = "1.1.0"
description = ""
authors = ["Kenneth V. Domingo <hello@kvdomingo.xyz>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.10"
Django = "<4.1"
aiohttp = "3.7.4.post0"
"discord.py" = "1.7.3"
django-filter = "^22.1"
djangorestframework = "^3.13.1"
gunicorn = {extras = ["gthread"], version = "^20.1.0"}
psycopg2 = "^2.9.3"
python-twitter = "^3.5"
requests = "^2.28.1"
requests-oauthlib = "^1.3.1"
sentry-sdk = "^1.9.5"
tqdm = "^4.64.0"
whitenoise = "^6.2.0"
dj-database-url = "^1.0.0"
python-dotenv = "^0.20.0"
loguru = "^0.6.0"
watchdog = "^2.1.9"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py310']
line-length = 120
