[tool.poetry]
name = "chaebot"
version = "1.3.0"
description = ""
authors = ["Kenneth V. Domingo <hello@kvdomingo.xyz>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.10"
Django = "4.0.4"
aiohttp = "^3.8.4"
"discord.py" = "^2.1.0"
django-filter = "^22.1"
djangorestframework = "3.14.0"
gunicorn = {extras = ["gevent"], version = "^20.1.0"}
python-twitter = "^3.5"
requests = "^2.28.2"
requests-oauthlib = "^1.3.1"
sentry-sdk = "^1.16.0"
tqdm = "^4.65.0"
whitenoise = "^6.4.0"
dj-database-url = "^1.2.0"
python-dotenv = "^0.20.0"
loguru = "^0.6.0"
watchdog = "^2.3.1"
click = "^8.1.3"
vlive = "^0.1.1"
psycopg2-binary = "^2.9.5"
google-cloud-firestore = "^2.10.0"
firebase-admin = "^6.1.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
isort = "^5.10.1"
jupyter = "^1.0.0"
notebook = "^6.5.2"
google-cloud-secret-manager = "^2.15.0"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ["py310"]
line-length = 120

[tool.isort]
profile = "black"
