version: '3'

env:
  NAME: chaebot
  VERSION:
    sh: git rev-parse --short HEAD

dotenv:
  - .env

tasks:
  default:
    desc: Build and start containers
    cmds:
      - docker compose -p {{.NAME}} up -d --build --remove-orphans {{.CLI_ARGS}}

  setup:
    desc: Run initial setup
    cmds:
      - poetry run python -m scripts.make_dotenv
      - poetry run python -m scripts.make_dotenvrc
      - task exec -- api python manage.py createsuperuser

  psql:
    desc: Access Postgres CLI
    cmds:
      - docker compose -p {{.NAME}} exec -- postgres psql -U $POSTGRESQL_USERNAME -d $POSTGRESQL_DATABASE

  exec:
    desc: Execute command in specified container
    cmds:
      - docker compose -p {{.NAME}} exec -- {{.CLI_ARGS}}

  restart:
    desc: Restart all containers
    cmds:
      - docker compose -p {{.NAME}} restart {{.CLI_ARGS}}

  logs:
    desc: Show Docker logs
    cmds:
      - docker compose -p {{.NAME}} logs --follow {{.CLI_ARGS}}

  stop:
    desc: Stop all containers
    cmds:
      - docker compose -p {{.NAME}} stop {{.CLI_ARGS}}

  clean:
    desc: Stop and remove all containers
    cmds:
      - docker compose -p {{.NAME}} down -v --remove-orphans
