"""remove VliveAccount model, add fields to Group model instead

Revision ID: 244d7b72f257
Revises: cc790dc4c69c
Create Date: 2020-07-17 23:00:02.264541+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244d7b72f257'
down_revision = 'cc790dc4c69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vliveaccount')
    op.add_column('group', sa.Column('vlive_channel_code', sa.String(length=255), nullable=True))
    op.add_column('group', sa.Column('vlive_channel_seq', sa.BigInteger(), nullable=True))
    op.add_column('group', sa.Column('vlive_last_seq', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'vlive_last_seq')
    op.drop_column('group', 'vlive_channel_seq')
    op.drop_column('group', 'vlive_channel_code')
    op.create_table('vliveaccount',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('channel_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('channel_seq', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_video_seq', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='vliveaccount_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vliveaccount_pkey')
    )
    # ### end Alembic commands ###
