"""rename Channel -> TwitterChannel

Revision ID: 6406c7517345
Revises: 5c6b26f1c575
Create Date: 2020-07-17 22:34:20.275380+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6406c7517345'
down_revision = '5c6b26f1c575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('channel', 'twitterchannel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('twitterchannel', 'channel')
    # ### end Alembic commands ###
