"""point foreignkeys to Group.name

Revision ID: 6c32903396a9
Revises: a112e83d763b
Create Date: 2020-07-11 22:11:27.966524+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c32903396a9'
down_revision = 'a112e83d763b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'group', ['name'])
    op.add_column('channel', sa.Column('group_name', sa.String(length=64), nullable=True))
    op.add_column('member', sa.Column('group_name', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'channel', 'group', ['group_name'], ['name'])
    op.create_foreign_key(None, 'member', 'group', ['group_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_column('member', 'group_name')
    op.drop_constraint(None, 'group', type_='unique')
    op.drop_constraint(None, 'channel', type_='foreignkey')
    op.drop_column('channel', 'group_name')
    # ### end Alembic commands ###
