"""remove extra foreignkeys

Revision ID: 75f440481a2a
Revises: 6c32903396a9
Create Date: 2020-07-11 22:42:02.112027+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f440481a2a'
down_revision = '6c32903396a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channel_group_name_fkey', 'channel', type_='foreignkey')
    op.drop_column('channel', 'group_name')
    op.drop_constraint('member_group_name_fkey', 'member', type_='foreignkey')
    op.drop_column('member', 'group_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('group_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_foreign_key('member_group_name_fkey', 'member', 'group', ['group_name'], ['name'])
    op.add_column('channel', sa.Column('group_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_foreign_key('channel_group_name_fkey', 'channel', 'group', ['group_name'], ['name'])
    # ### end Alembic commands ###
