"""add birthday field to Member

Revision ID: 9aa10724f582
Revises: bf19abb62565
Create Date: 2020-11-29 00:42:27.562297+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa10724f582'
down_revision = 'bf19abb62565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('birthday', sa.Date(), nullable=True))
    op.drop_constraint('channel_channel_id_key', 'twitterchannel', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('channel_channel_id_key', 'twitterchannel', ['channel_id'])
    op.drop_column('member', 'birthday')
    # ### end Alembic commands ###
