"""add reverse relations in Group and Member models

Revision ID: a112e83d763b
Revises: c4a001d102a5
Create Date: 2020-07-11 17:56:28.035190+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a112e83d763b'
down_revision = 'c4a001d102a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
