"""add last_tweet_id toTwitterAccount

Revision ID: bf19abb62565
Revises: 244d7b72f257
Create Date: 2020-07-18 19:20:12.940540+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf19abb62565'
down_revision = '244d7b72f257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitteraccount', sa.Column('last_tweet_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitteraccount', 'last_tweet_id')
    # ### end Alembic commands ###
