# Generated by Django 3.1.4 on 2020-12-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('vlive_channel_code', models.CharField(max_length=32)),
                ('vlive_channel_seq', models.BigIntegerField()),
                ('vlive_last_seq', models.BigIntegerField()),
                ('twitter_user_name', models.CharField(blank=True, max_length=16)),
                ('instagram_user_name', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=16)),
                ('given_name', models.CharField(max_length=16)),
                ('family_name', models.CharField(max_length=16)),
                ('english_name', models.CharField(max_length=16, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.group')),
            ],
            options={
                'ordering': ['group__name', 'stage_name'],
            },
        ),
        migrations.CreateModel(
            name='VliveSubscribedChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.group')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterMediaSubscribedChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.group')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterMediaSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=16, unique=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=32)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='bot.member')),
            ],
            options={
                'verbose_name_plural': 'member aliases',
                'ordering': ['member__group__name', 'member__stage_name', 'alias'],
            },
        ),
        migrations.CreateModel(
            name='GroupAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=16, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='bot.group')),
            ],
            options={
                'verbose_name_plural': 'group aliases',
                'ordering': ['group__name', 'alias'],
            },
        ),
    ]
