# Generated by Django 3.1.4 on 2020-12-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='groupalias',
            options={'verbose_name_plural': 'group aliases'},
        ),
        migrations.AlterModelOptions(
            name='memberalias',
            options={'verbose_name_plural': 'member aliases'},
        ),
        migrations.AlterField(
            model_name='group',
            name='instagram_user_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
