# Generated by Django 3.1.4 on 2020-12-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20201225_0413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupalias',
            options={'ordering': ['group__name', 'alias'], 'verbose_name_plural': 'group aliases'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['group__name', 'stage_name']},
        ),
        migrations.AlterModelOptions(
            name='memberalias',
            options={'ordering': ['member__group__name', 'alias'], 'verbose_name_plural': 'member aliases'},
        ),
        migrations.AddField(
            model_name='member',
            name='english_name',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
