# Generated by Django 3.1.4 on 2020-12-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_twittermediasource_last_tweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlivesubscribedchannel',
            name='dev_channel',
            field=models.BooleanField(default=False),
        ),
    ]
