# Generated by Django 3.1.4 on 2020-12-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20201225_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberalias',
            name='alias',
            field=models.CharField(max_length=32),
        ),
    ]
