# Generated by Django 3.1.4 on 2021-01-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_activate_pg_ext_20201226_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittermediasubscribedchannel',
            name='channel_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='vlivesubscribedchannel',
            name='channel_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='twittermediasubscribedchannel',
            unique_together={('channel_id', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='vlivesubscribedchannel',
            unique_together={('channel_id', 'group')},
        ),
    ]
