# Generated by Django 3.1.4 on 2021-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20210106_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='english_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
