# Generated by Django 3.1.4 on 2021-01-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20210106_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittermediasource',
            name='last_tweet_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
