# Generated by Django 3.1.4 on 2021-01-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20210107_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['group__name', 'birthday', 'stage_name']},
        ),
        migrations.AddField(
            model_name='group',
            name='korean_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
