# Generated by Django 3.1.4 on 2021-01-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20210108_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='native_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
