# Generated by Django 3.1.4 on 2021-01-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_member_native_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='korean_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='chinese_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='korean_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='native_name',
        ),
    ]
