# Generated by Django 4.0.8 on 2022-11-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20211104_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='vlive_channel_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
