# Generated by Django 4.0.4 on 2023-02-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_remove_group_vlive_channel_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField()),
                ('channel_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField(null=True)),
            ],
            options={
                'unique_together': {('channel_id', 'message_id')},
            },
        ),
    ]
