# Generated by Django 4.0.4 on 2023-02-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_schedulesubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesubscriber',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
