# Generated by Django 4.0.4 on 2023-02-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_alter_schedulesubscriber_message_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulesubscriber',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='schedulesubscriber',
            name='message_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='schedulesubscriber',
            unique_together={('guild_id', 'channel_id', 'message_id')},
        ),
    ]
