# Generated by Django 4.1.7 on 2023-04-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0021_alter_schedulesubscriber_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmoteCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="StickerCache",
            fields=[
                ("id", models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("url", models.URLField()),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StickerUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("sticker", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bot.stickercache")),
            ],
            options={
                "ordering": ["-timestamp"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmoteUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("emote", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bot.emotecache")),
            ],
            options={
                "ordering": ["-timestamp"],
                "abstract": False,
            },
        ),
    ]
