# Generated by Django 4.1.7 on 2023-04-06 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0022_emotecache_stickercache_stickerusage_emoteusage"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCache",
            fields=[
                ("id", models.PositiveBigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("discriminator", models.CharField(max_length=8)),
                ("avatar", models.URLField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="emoteusage",
            name="emote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="usage", to="bot.emotecache"
            ),
        ),
        migrations.AlterField(
            model_name="stickercache",
            name="id",
            field=models.PositiveBigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="stickerusage",
            name="sticker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="usage", to="bot.stickercache"
            ),
        ),
        migrations.AddField(
            model_name="emoteusage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emote_usage",
                to="bot.usercache",
            ),
        ),
        migrations.AddField(
            model_name="stickerusage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sticker_usage",
                to="bot.usercache",
            ),
        ),
    ]
