# Generated by Django 4.1.7 on 2023-04-06 10:09

import bot.models.emote_cache
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0023_usercache_alter_emoteusage_emote_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emoteusage",
            name="timestamp",
            field=models.DateTimeField(default=bot.models.emote_cache.timestamp_factory),
        ),
        migrations.AlterField(
            model_name="stickerusage",
            name="timestamp",
            field=models.DateTimeField(default=bot.models.emote_cache.timestamp_factory),
        ),
    ]
