# Generated by Django 4.1.7 on 2023-04-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0024_alter_emoteusage_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emotecache",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="emotecache",
            name="name",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emotecache",
            name="url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emotecache",
            name="id",
            field=models.PositiveBigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
