# Generated by Django 4.1.7 on 2023-04-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0025_alter_emotecache_options_emotecache_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotecache",
            name="channel_id",
            field=models.PositiveBigIntegerField(db_index=True, default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emotecache",
            name="guild_id",
            field=models.PositiveBigIntegerField(db_index=True, default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stickercache",
            name="channel_id",
            field=models.PositiveBigIntegerField(db_index=True, default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stickercache",
            name="guild_id",
            field=models.PositiveBigIntegerField(db_index=True, default=0, unique=True),
            preserve_default=False,
        ),
    ]
